updated backupManualPlace_State.cpp
Team302/2024Crescendo pull request #254
Opened 2024-01-31 01:03 UTC by ImAPenguin56

2024-01-31 03:15 UTC, Tan560 approved these changes

2024-01-31 03:46 UTC, Tan560 reviewed
Add an OR condition of (m_mechanism->GetCurrentState() == backupManaulLaunch && m_mechanism->m_scoringMode == RobotStateChanges::ScoringMode::Placer)

2024-01-31 03:46 UTC, Tan560 commented on src/main/cpp/mechanisms/noteManager/decoratormods/noteManager_backupManualPlace_State.cpp
> +	return (considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::MANUAL_MODE) && m_mechanism->m_scoringMode == RobotStateChanges::ScoringMode::Placer);
Add an OR condition of  (m_mechanism->GetCurrentState() == backupManaulLaunch &&  m_mechanism->m_scoringMode == RobotStateChanges::ScoringMode::Placer)

2024-01-31 03:51 UTC, Tan560 requested changes
Add an OR condition of (m_mechanism->GetCurrentState() == backupManaulLaunch && m_mechanism->isPlacerMode())

2024-02-01 04:37 UTC, Tan560 requested changes

2024-02-01 04:37 UTC, Tan560 commented on src/main/cpp/mechanisms/noteManager/decoratormods/noteManager_backupManualPlace_State.cpp
> +	return (considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::MANUAL_MODE) && m_mechanism->m_scoringMode == RobotStateChanges::ScoringMode::Placer);
Also update from Main and then replace
m_mechanism->m_scoringMode == RobotStateChanges::ScoringMode::Placer
with
m_mechanism->isPlacerMode()

2024-02-03 15:27 UTC, ElliotBayer commented
Deleting branch and creating new one from Main

2024-02-03 15:27 UTC, closed without merging