Assigned Control Data in Init and  updated targets in Run
Team302/2024Crescendo pull request #267
Opened 2024-01-31 05:22 UTC by Tan560

Please let me know if you see any issues with the way I set the controlData and targets of the motors. If this looks okay with you, I can write a bunch of stories/tasks for the rest of the states.

2024-01-31 18:37 UTC, witcpalek requested changes
I really don't like this ...

Why is the code generator making all of the motors public (and not named correctly)?
Why are we making the state changes attribute public?

2024-01-31 19:02 UTC, Tan560 commented
The name is just what we have called all of the motors, we can change that if you want. But we just went with camel case for the motors and sensors. How should it be done? I guess is this something we can live with for now? We have a robot coming over in a couple days and I don't know if we can really redo all of this. We can talk more tonight if it is easier.

2024-02-02 03:14 UTC, witcpalek requested changes

2024-02-02 03:14 UTC, witcpalek commented on src/main/cpp/mechanisms/noteManager/decoratormods/noteManager_backupManualLaunch_State.cpp
> +	m_mechanism->Elevator->SetControlConstants(0, *m_mechanism->percentOutput);
need to move percentOutput to be a private variable and then access it via an accessor

2024-02-02 03:14 UTC, witcpalek commented on src/main/cpp/mechanisms/noteManager/decoratormods/noteManager_backupManualLaunch_State.cpp
> +	m_mechanism->frontIntake->Set(TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::BACKUP_FRONT_INTAKE));
motor need to be private and accessed via accessors

2024-02-03 16:15 UTC, Tan560 commented
Update Code Gen and not needed anymore

2024-02-03 16:15 UTC, closed without merging