87 create field constants file
Team302/2024Crescendo pull request #377
Opened 2024-02-05 23:43 UTC by ImAPenguin56

2024-02-08 23:23 UTC, nickfrisch requested changes
Make sure to update from main

2024-02-08 23:23 UTC, nickfrisch commented on build.gradle
> +def includeDesktopSupport = true
Can run the command Change Desktop Build Confguration or similar name to set to false, or manually edit

2024-02-08 23:23 UTC, nickfrisch commented on src/main/cpp/Robot.cpp
> +    m_fieldConsts = new FieldConsts();
Remove this testing code

2024-02-08 23:23 UTC, nickfrisch commented on src/main/cpp/Robot.cpp
> +    m_field->AddPose("Blue Speaker", m_fieldConsts->GetFieldElement(FieldConsts::FIELD_ELEMENT::BLUE_SPEAKER).ToPose2d());
Remove from here to line 185, testing code that shouldn't be in main

2024-02-08 23:23 UTC, nickfrisch commented on src/main/cpp/Robot.h
> +class FieldConsts;
Can remove for now, testing code

2024-02-08 23:23 UTC, nickfrisch commented on src/main/cpp/Robot.h
> +    FieldConsts *m_fieldConsts;
Can remove, testing code

2024-02-08 23:23 UTC, nickfrisch commented on src/main/cpp/utils/FieldConsts.cpp
> +FieldConsts::FieldConsts()
Rename to FieldConstants

2024-02-08 23:23 UTC, nickfrisch commented on src/main/cpp/utils/FieldConsts.h
> +    FieldConsts();
Make FieldConstants a singleton

2024-02-08 23:36 UTC, nickfrisch requested changes

2024-02-08 23:36 UTC, nickfrisch commented on src/main/cpp/Robot.cpp
> +#include <frc/geometry/Pose3d.h>
This include can be removed

2024-02-08 23:36 UTC, nickfrisch commented on src/main/cpp/Robot.cpp
> +#include <utils\FieldConstants.h>
This include can be removed

2024-02-10 03:34 UTC, nickfrisch requested changes
Update from main and validate build, approved after that

2024-02-10 14:15 UTC, reslip1 commented
> Update from main and validate build, approved after that

I merged changes from main that preventing merging and build is good.

2024-02-10 20:12 UTC, reslip1 approved these changes

2024-02-13 01:29 UTC, merged