304 clean up primitiveparsers pipeline attributes
Team302/2024Crescendo pull request #400
Opened 2024-02-07 00:16 UTC by alyssaperson1

Fixes issue #304

2024-02-07 00:20 UTC, Frank0624789 approved these changes

2024-02-07 18:42 UTC, witcpalek requested changes

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/DragonVision/DragonCamera.h
> +        APRIL_TAG
Why APRIL_TAG?  Also, might make UNKNOWN -1 as 0 is more often used in an enum

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/DragonVision/DragonCamera.h
> +    enum VISION_ALIGNMENT
We should create this enum in PrimitiveParams not Dragon Camera

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/DragonVision/DragonCamera.h
> +        VISION_ALIGNMENT visionAlignment,      /// <I> enum for pipeline
Don't change the signature for DragonCamera, we'll cast the enum values when calling vision stuff

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/DragonVision/DragonCamera.h
> +    VISION_ALIGNMENT GetVisionAlignment() const { return m_visionAlignment; }
Don't change DragonCamera

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/auton/PrimitiveParams.h
> -        DragonCamera::PIPELINE pipelineMode,
Create our own enum in PrimitiveParams that we use to create the PrimitiveParams instead of using DragonCamera's enum

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/auton/PrimitiveParams.h
>      ZoneParamsVector m_zones;
Add an attribute for the vision target

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/auton/PrimitiveParser.cpp
> +#include "DragonVision/DragonCamera.h"
remove

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/auton/PrimitiveParser.cpp
> +    map<string, DragonCamera::VISION_ALIGNMENT> xmlStringToVisionAlignmentEnumMap{
Use new enum that you create in PrimitiveParams

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/auton/PrimitiveParser.cpp
> +                    auto visionAlignmentmode = DragonCamera::VISION_ALIGNMENT::UNKNOWN;
use new enum

2024-02-07 18:42 UTC, witcpalek commented on src/main/cpp/auton/PrimitiveParser.cpp
> +                                                                         zones // vector of all zones included as part of the path
add in the vision alignment option

2024-02-07 18:42 UTC, witcpalek commented on src/main/deploy/auton/auton.dtd
> +          visionAligment          ( UNKNOWN | NOTE | SPEAKER ) "APRIL_TAG"
Default value ("APRIL_TAG") should be one of the options.  In this case "UNKNOWN" would be appropriate.

2024-02-08 14:40 UTC, witcpalek requested changes

2024-02-11 23:05 UTC, witcpalek approved these changes

2024-02-11 23:06 UTC, witcpalek commented on src/main/cpp/DragonVision/DragonCamera.h
>  #include "frc/geometry/Pose3d.h"
fixed

2024-02-11 23:06 UTC, witcpalek commented on src/main/cpp/DragonVision/DragonVision.cpp
> -bool DragonVision::SetPipeline(DragonCamera::PIPELINE mode, CAMERA_POSITION position)
fixed

2024-02-11 23:25 UTC, witcpalek approved these changes

2024-02-11 23:25 UTC, merged