396 test getvisiondatafromnote
Team302/2024Crescendo pull request #501
Opened 2024-02-17 20:55 UTC by reslip1

2024-02-18 02:04 UTC, witcpalek requested changes

2024-02-18 14:52 UTC, reslip1 commented on src/main/deploy/chassis/swervemodule_9997.xml
> +    proportional="5.0"
this hasn't been tuned yet. It is a placeholder for this bot.

2024-02-18 14:52 UTC, reslip1 commented on src/main/cpp/DragonVision/DragonVision.cpp
> +	if (true){
true. fixed it.

2024-02-18 15:26 UTC, witcpalek submitted a review, later dismissed

2024-02-18 15:26 UTC, witcpalek commented
Please fix build errors

2024-02-18 16:06 UTC, reslip1 commented
> Please fix build errors

fixed

2024-02-18 20:53 UTC, witcpalek commented
Please merge

2024-02-19 16:14 UTC, reslip1 commented
> Please merge

merged

2024-02-19 16:55 UTC, witcpalek commented
Merge is bad; your modifying files that were deleted and deleting newly added files.

Also, should there be changes in code generator files?

2024-02-19 16:58 UTC, reslip1 commented
> Merge is bad; your modifying files that were deleted and deleting newly added files.
> 
> Also, should there be changes in code generator files?

This was commits to catch up to deletes/changes that were done in main. The files changes will still only be the changes compared to main.

2024-02-19 17:11 UTC, witcpalek commented
> > Merge is bad; your modifying files that were deleted and deleting newly added files.
> > Also, should there be changes in code generator files?
> 
> This was commits to catch up to deletes/changes that were done in main. The file changes will still only be the changes compared to main.
There are merge lines in the files and many changes in code generator stuff.  Did you regenerate using code generator?

<<<<<<< HEAD
// This file was automatically generated by the Team 302 code generator version 1.2.3.5
// Generated on Saturday, February 17, 2024 3:03:24 PM
=======
// This file was automatically generated by the Team 302 code generator version 1.3.0.1
// Generated on Sunday, February 18, 2024 10:15:34 PM
>>>>>>> main

#include <string>

#include "PeriodicLooper.h"
#include "utils/logging/Logger.h"
#include "configs/RobotConfigMgr.h"
#include "configs/RobotConfigChassisBot_9997.h"
#include "configs/RobotElementNames.h"
#include "DragonVision/DragonPhotonCam.h"
#include "DragonVision/DragonVision.h"

using std::string;

void RobotConfigChassisBot_9997::DefineMechanisms()
{

}

<<<<<<< HEAD
=======
void RobotConfigChassisBot_9997::DefineLEDs()
{


}

>>>>>>> main

2024-02-19 17:16 UTC, reslip1 commented
> > > Merge is bad; your modifying files that were deleted and deleting newly added files.
> > > Also, should there be changes in code generator files?
> > 
> > 
> > This was commits to catch up to deletes/changes that were done in main. The file changes will still only be the changes compared to main.
> > There are merge lines in the files and many changes in code generator stuff.  Did you regenerate using code generator?
> 
> # <<<<<<< HEAD
> // This file was automatically generated by the Team 302 code generator version 1.2.3.5
> // Generated on Saturday, February 17, 2024 3:03:24 PM
> 
> // This file was automatically generated by the Team 302 code generator version 1.3.0.1 // Generated on Sunday, February 18, 2024 10:15:34 PM
> 
> > > > > > > > main
> 
> #include
> 
> #include "PeriodicLooper.h" #include "utils/logging/Logger.h" #include "configs/RobotConfigMgr.h" #include "configs/RobotConfigChassisBot_9997.h" #include "configs/RobotElementNames.h" #include "DragonVision/DragonPhotonCam.h" #include "DragonVision/DragonVision.h"
> 
> using std::string;
> 
> void RobotConfigChassisBot_9997::DefineMechanisms() {
> 
> }
> # <<<<<<< HEAD
> 
> void RobotConfigChassisBot_9997::DefineLEDs() {
> 
> }
> 
> > > > > > > > main

thanks! I did see those in the latest build failure. Was still in the process of doing commits for the large merge and those got caught up in the changes. Should be fixed and building now.

2024-02-19 23:47 UTC, muscatd75 approved these changes

2024-02-20 01:35 UTC, muscatd75 approved these changes

2024-02-20 01:46 UTC, merged