photonvision updated to version 6
Team302/2024Crescendo pull request #548
Opened 2024-02-20 01:56 UTC by notcharlie2026

2024-02-20 04:20 UTC, witcpalek requested changes

2024-02-20 04:20 UTC, witcpalek commented on src/main/cpp/configs/RobotConfigChassisBot_99979997.cpp
> +// Generated on Monday, February 19, 2024 7:49:31 PM
Something isn't looking right, why is this file gamed 99979997 again; its currently 9997  Did you not use the latest code generator to modify the code generator files?

2024-02-21 01:42 UTC, reslip1 commented on src/main/cpp/configs/RobotConfigChassisBot_9997.cpp
> -
when you ran generator you didn't have the limelight-pintake, so it removed it for this robot

2024-02-21 01:44 UTC, reslip1 commented on vendordeps/photonlib.json
>  {
why did this change?

2024-02-21 01:47 UTC, reslip1 commented
@nickfrisch , @Tan560 , we may want to redo this branch after the other merge from main

2024-02-21 23:49 UTC, nickfrisch requested changes
Remove all changes other than photonlib.json

2024-02-21 23:49 UTC, nickfrisch commented on codeGenerator/configuration/RobotConfig/2024Crescendo.xml
Will be included in @Tan560's big merge

2024-02-22 00:45 UTC, reslip1 commented
This was added to the main branch by @Tan560 and @muscatd75

2024-02-22 00:45 UTC, closed without merging