added a check for all sensors being off before going into ready in teleopinit
Team302/2024Crescendo pull request #614
Opened 2024-02-29 00:21 UTC by JamesLimothy

closes #604

2024-02-29 18:05 UTC, Tan560 commented
@witcpalek  This all looks good to me, but I don't know if I am missing something/we should be doing this a different way. Please check and approve if you agree.

Thanks

2024-02-29 19:07 UTC, witcpalek requested changes

2024-02-29 19:07 UTC, witcpalek commented on src/main/cpp/Robot.cpp
> +                              (m_noteManagerGen->getlauncherSensor()->Get() == false) &&
inconsistent variable names; m_noteManagerGet has not been initialized yet.  There is no guarantee that getxxxsensor will not return a nullptr, so it needs to be checked before calling the get method.  

Then  boolean compares don't need == false, just user ! before it

I don't think you need a classwide variable either

2024-02-29 19:07 UTC, witcpalek commented on src/main/cpp/Robot.h
> +    noteManagerGen *m_noteManagerGen;
Don't need this file changed, just use a local variable in the one method that needs the notemanager

2024-03-02 05:00 UTC, Tan560 commented
@witcpalek  Please pull this down too and we can test this tomorrow, I have merged it with main

2024-03-05 22:19 UTC, Tan560 approved these changes

2024-03-05 22:20 UTC, Tan560 commented
Tested on 9999 and works

2024-03-06 00:18 UTC, witcpalek approved these changes

2024-03-06 00:29 UTC, merged